# Generated by Django 4.1.4 on 2023-10-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsa', models.IntegerField(default='0')),
                ('project', models.IntegerField(default='0')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
